version: 2.0.0.{build}

image: Visual Studio 2022

environment:
  packageVersion: 2.0.0

init:
- ps: echo "$env:packageVersion"
- ps: $env:nugetVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: echo "$env:nugetVersion"

configuration: Release

platform: Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(nugetVersion)
  assembly_version: '{version}'
  file_version: $(nugetVersion)
  informational_version: $(nugetVersion)

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

after_build:
- ps: dotnet pack Promat.EmailSender\Promat.EmailSender.Smtp.csproj --configuration Release --include-symbols --no-build --output "$env:APPVEYOR_BUILD_FOLDER"
- ps: dotnet pack Promat.EmailSender\Promat.EmailSender.MailMaker.csproj --configuration Release --include-symbols --no-build --output "$env:APPVEYOR_BUILD_FOLDER"

artifacts:
- path: '*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: +N9eF1k4VKJ2M9M0bMXeOIah6bzgh6BYPlsmDR5yq34bmLOX+kJ8EnK4tod572z6
  skip_symbols: true
  on:
    APPVEYOR_REPO_TAG: true
